import type { BubbleStudioItem } from "./types";

/**
 * Realistische Mock-Daten für das Bubble Studio Lab.
 * Später ersetzt durch: bubbles-Query + Aggregation über analytics_events.
 * Huber Arena / Quickborn / Demo sind als geschützte Piloten markiert.
 */
export const MOCK_BUBBLES: BubbleStudioItem[] = [
  {
    id: "mock-mboa",
    organizationId: "org-intern",
    name: "MBOA Festival 2026",
    slug: "mboa-festival",
    partnerName: "MBOA Events GmbH",
    eventType: "Festival",
    eventDate: "2026-07-18",
    location: "Hamburg, Stadtpark",
    status: "live",
    templateId: "festival_sponsor",
    primaryColor: "#5b21b6",
    accentColor: "#f59e0b",
    kpis: { scans: 4820, landingViews: 4380, liveViews: 3120, participations: 2260, leads: 610, rewardClaims: 1480, redemptions: 890, sponsorClicks: 720 },
    isProtectedPilot: false,
    isTemplate: false,
  },
  {
    id: "mock-huber",
    organizationId: "org-huber",
    name: "Huber Arena",
    slug: "huber-arena",
    partnerName: "TSV Huber",
    eventType: "Sportverein",
    eventDate: "2026-07-05",
    location: "Huber Arena",
    status: "live",
    templateId: "club_matchday",
    primaryColor: "#0058be",
    accentColor: "#b61722",
    kpis: { scans: 640, landingViews: 590, liveViews: 470, participations: 350, leads: 0, rewardClaims: 210, redemptions: 140, sponsorClicks: 95 },
    isProtectedPilot: true,
    isTemplate: false,
  },
  {
    id: "mock-quickborn",
    organizationId: "org-quickborn",
    name: "Public Viewing Quickborn",
    slug: "public-viewing-quickborn",
    partnerName: "Stadt Quickborn",
    eventType: "Public Viewing",
    eventDate: "2026-06-28",
    location: "Quickborn, Marktplatz",
    status: "ended",
    templateId: "public_viewing",
    primaryColor: "#dd0000",
    accentColor: "#f7c800",
    kpis: { scans: 1930, landingViews: 1760, liveViews: 1410, participations: 980, leads: 240, rewardClaims: 560, redemptions: 380, sponsorClicks: 310 },
    isProtectedPilot: true,
    isTemplate: false,
  },
  {
    id: "mock-club-template",
    organizationId: "org-club",
    name: "Club Matchday Template",
    slug: "club-matchday-template",
    partnerName: "—",
    eventType: "Sportverein",
    eventDate: "",
    location: "",
    status: "draft",
    templateId: "club_matchday",
    primaryColor: "#b61722",
    accentColor: "#141b2b",
    kpis: { scans: 0, landingViews: 0, liveViews: 0, participations: 0, leads: 0, rewardClaims: 0, redemptions: 0, sponsorClicks: 0 },
    isProtectedPilot: false,
    isTemplate: true,
  },
  {
    id: "mock-bar-template",
    organizationId: null,
    name: "Bar Night Template",
    slug: "bar-night-template",
    partnerName: "—",
    eventType: "Bar",
    eventDate: "",
    location: "",
    status: "draft",
    templateId: "bar_night",
    primaryColor: "#0f172a",
    accentColor: "#e11d48",
    kpis: { scans: 0, landingViews: 0, liveViews: 0, participations: 0, leads: 0, rewardClaims: 0, redemptions: 0, sponsorClicks: 0 },
    isProtectedPilot: false,
    isTemplate: true,
  },
  {
    id: "mock-sponsor-template",
    organizationId: null,
    name: "Sponsor Activation Template",
    slug: "sponsor-activation-template",
    partnerName: "Sparkasse Musterstadt",
    eventType: "Sponsor-Aktivierung",
    eventDate: "2026-08-14",
    location: "Musterstadt",
    status: "preview",
    templateId: "sponsor_activation",
    primaryColor: "#065f46",
    accentColor: "#0ea5e9",
    kpis: { scans: 45, landingViews: 41, liveViews: 28, participations: 12, leads: 4, rewardClaims: 6, redemptions: 0, sponsorClicks: 9 },
    isProtectedPilot: false,
    isTemplate: true,
  },
];
